### ISSUE TITLE
Implement in Go or Rust

### ISSUE THREAD

**Issue by peredwardsson** [felrock/aoc2022#1]
Hi team, 

Per discussion, consider a more nicer language.

Thanks,
Lead

**Comment by felrock** [comment]
Hello,

Thanks for your inquiry, I will forward it to tech team and we will come back to you with an estimate. In the meantime, it would be pleasant if you could also provide solutions in this years challenge, in whatever language of your choosing. Because of right now I see **0** uploaded solutions. 

/F
